#2
name: CI
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Publish test coverage results
      uses: PavanMudigonda/jacoco-reporter@v4.5
      with:
        coverage_results_path: 'jacoco.xml'
        coverage_report_title: 'Test coverage results'
        coverage_report_name: 'Test coverage results'
        github_token: ${{ secrets.GITHUB_TOKEN }}      
